ss (#1)
* Fix visualize activations (#1211)

Fix visualize activations (Squashed 4 commits by @keineahnung2345)

# Get activations of a few sample layers
activations = model.run_graph([image], [
    ("input_image",        model.keras_model.get_layer("input_image").output)
])
leads to the error:
InvalidArgumentError: input_image:0 is both fed and fetched.

Revise the code according to https://stackoverflow.com/questions/39307108/placeholder-20-is-both-fed-and-fetched

* Fix typo in config.py

* Fix typo in rpn_class_loss_graph

Fix https://github.com/matterport/Mask_RCNN/issues/870

* Reversed order (1) and (2) in installation

Reference to #1255

* remove unused code (#1227)

Remove unused code